// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cascfuzibfifbhabujbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhc2NmdXppYmZpZmJoYWJ1amJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDk4NTksImV4cCI6MjA2NTIyNTg1OX0.GJY4QMdjgxhFyGIC8MCrZJPu5OYFQDKTuJQRfgHQvPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);